id: P4F154AA6
initial_creation_type: ocr
source_metadata:
  volumes:
    f590bfd50b27479e8a9ed5344cb8de9d:
      base_file: v097.txt
      image_group_id: I1PD95942
      title: ཚད་མའི་བསྟན་བཅོས་རིགས་པ་ལ་འཇུག་པ།
      total_pages: 1198
      volume_number: 97
